### ISSUE TITLE
Avatars not compiling while script is imported.

### ISSUE THREAD

**Issue by AbsolofDarkness** [artieficial/ApplyAccessories#1]
After importing script, attempting to Build and Test avatar will result in this set of errors.
![Screenshot 2021-12-10 135656](https://user-images.githubusercontent.com/20271967/145633935-78393956-b2c3-4ddd-be97-804fd00bdcc5.png)

This can be fixed by making sure the script is in an Editor folder in the root of the project. This should be mentioned in the README, or making sure that the Editor folder is included when importing the script.

**Comment by artieficial** [comment]
Currently trying to address this alongside other QOL updates.

**Comment by artieficial** [comment]
Fixed as of v1.1.0
