### ISSUE TITLE
Not sure if this is an issue or not.

### ISSUE THREAD

**Issue by Purriku** [artieficial/ApplyAccessories#12]
New to all of this. I have three accessories id like to add to my avatar but they only have meshes and prefabs. in the Heirarchy they do not have armatures. Attempting to apply them will hide them like normal but it does not generate parameters or controls in the selected expression menu. Not sure if there is something I need to do or they are simply incompatible.
![image](https://user-images.githubusercontent.com/87593087/167235717-69e0c737-f764-401e-a41b-be11f0cd0ee4.png)

**Comment by Krunklehorn** [comment]
The author doesn't seem to be replying so I'll try to help instead.

I'm guessing by the name of this accessory that it isn't supposed to be dynamic and can simply be parented to your avatar's neck bone.

If it _is_ supposed to have an armature, you need to select the asset in the project tab and set it's rig type to Generic.

**Comment by artieficial** [comment]
You will need to add those directly under the armature. Aka your necklace should be placed under you neck bone, your aviators under your head bone, etc.
