### ISSUE TITLE
Forces you to let it make a toggle

### ISSUE THREAD

**Issue by BamberBoozler** [artieficial/ApplyAccessories#2]
If you don't set a Menu under Menu Options, the application will fail.
I dont always want to make a new toggle, as an example, if ive imported a new FBX, I want to use all my old menu's and existing toggles, but be able to apply the clothing.
I am of course able to let it make a toggle, and then go through and delete it and all the Params & animations related to it.
But would be nice to have the option to not have to do that.

**Comment by artieficial** [comment]
Fix will be in newest version.
