### ISSUE TITLE
Incorrect Armature Hierarchy after merge

### ISSUE THREAD

**Issue by BamberBoozler** [artieficial/ApplyAccessories#3]
![Untitled](https://user-images.githubusercontent.com/50951969/147947140-66953287-9a6a-498d-9e17-7c72cba91509.jpg)

**Comment by artieficial** [comment]
Please message me on Discord (found you describing your issue on the Kitavali server)

Not quite sure where this issue is coming from and knowing which warmer asset this is may help me solve the problem (I can pay for the asset for testing purposes if it isn't free).
