### ISSUE TITLE
When I hit the Apply Changes Button it doesn't do what its meant to.

### ISSUE THREAD

**Issue by AvienReactor** [artieficial/ApplyAccessories#5]
Hi, I've been trying to figure out a solution as to why I can't get the plugin to work for my avatar. I have my basic avatar already setup and working for VR and I wanted to find a faster way of adding clothes to him. So I took his armature and rigged a shirt on it. I then brought the new shirt with its armature into unity and followed the process from this video [https://youtu.be/d1GgVg75NGA](url). But when I hit apply the shirt is still separated from my avatar and the only change I can find is the name of the shirt.

Unity Version: 2019.4.31f1 / VRChat SDK3

P.S. In the pictures I moved the two models apart to show that they're separated. The character also already has dynamic bones

![image](https://user-images.githubusercontent.com/59672605/149073848-30a7edc9-baba-4011-8737-8a202cde9f77.png)
![image](https://user-images.githubusercontent.com/59672605/149074057-4d1744a1-3a84-4308-b203-796908ded788.png)

I just found an error code that I get when I try it.
![image](https://user-images.githubusercontent.com/59672605/149074956-f0af4244-6e6c-43ff-a3d1-c2e327661b42.png)

**Comment by timsoarer** [comment]
I have the exact same issue with a different avatar, it just creates a clone and throws an index out of range exception.
![image](https://user-images.githubusercontent.com/85484126/149790208-45b0bc30-8c3f-4b50-bb66-dcd47bf757e0.png)
After hitting apply.
![image](https://user-images.githubusercontent.com/85484126/149790479-414ec391-0031-4ee1-9739-3ce8bc8aa478.png)
The armature for the accessory has the exact same bones with the same names as the avatar, I tried doing it with Don't Reuse Bones enabled and disabled.

**Comment by artieficial** [comment]
Working on a fix, should be up soon

**Comment by artieficial** [comment]
Fixed as of of v1.1.6, sorry for the delay

**Comment by timsoarer** [comment]
was just about to commit a fix when I saw that it was already closed XD

**Comment by AvienReactor** [comment]
Thank you
