### ISSUE TITLE
Object warping into avatar weirdly

### ISSUE THREAD

**Issue by GameKuchen** [artieficial/ApplyAccessories#7]
I tried to add a Harness to my avatar but as soon as I hit apply and try to toggle it on it's just weirdly inside my Avatar. 
I've also tried using "Don't Reuse Bones" 
but that didn't work either.

![Bild_2022-01-26_170615](https://user-images.githubusercontent.com/49527417/151200267-c3e6f240-38ef-4285-9c38-14026e323dfc.png)
![Bild_2022-01-26_170601](https://user-images.githubusercontent.com/49527417/151200227-87fbae59-74bd-4e44-ba1d-a2385a8e3bf6.png)

**Comment by artieficial** [comment]
Fixed as of version 1.1.7, double checked using Rexouium + Harness asset (looks like thats the one you have here)
